### ISSUE TITLE
get eNanoMapper tutorial listed in TeSS

### ISSUE THREAD

**Issue by egonw** [egonw/ELIXIR-Tox#10]
This week [the TeSS team](https://github.com/ElixirTeSS) showed how (see https://github.com/enanomapper/tutorials/pull/11) to extend the Markdown tutorials with BioSchemas annotation, and they suggested to set up crontab to crawl the tutorials to mine this annotation.

For us, the following tasks are:

- [x] verify annotation shows up as expected in TeSS
- [x] add annotation to all Markdown tutorials
- [x] improve annotation
- [x] provide experiences as user feedback to TeSS

**Comment by schymane** [comment]
(How) can we use this TeSS annotation in R packages ... a few examples
(a) in R packages documented with roxygen available in github (not on CRAN/BioC)
(b) in BioConductor R packages
(c) in vignettes

**Comment by schymane** [comment]
The existing TeSS categories will likely need some extensions to cover our use cases, e.g. 
- toxicity
- metabolomics / exposomics / small molecules
- cheminformatics

Are these topics "created" during documentation submission, or does the ontology need to be extended first?

**Comment by egonw** [comment]
Additional info: https://twitter.com/ElixirTess/status/996768133783449600

**Comment by egonw** [comment]
@schymane, some terms are already in EDAM, and I think we can use those immediately:

* toxicology:  http://edamontology.org/topic_2840
* cheminformatics: http://edamontology.org/topic_2258
* metabolomics: http://edamontology.org/topic_3172

**Comment by egonw** [comment]
I'm meeting with Niall Beard in the next coffee break about becoming a "content provider".

**Comment by egonw** [comment]
We set up a eNanoMapper "content provider" (each project should, for branding purposes and funder requirements): https://tess.elixir-europe.org/content_providers/enanomapper

The first course shows up now, but the automation needs some more attention... (exciting!)

**Comment by egonw** [comment]
@njall, please let me know if I can be of assistance... I'd be interested in seeing your scraper code and see if I can make sense of the problem...

**Comment by njall** [comment]
Hi, 

I've [written a scraper](https://github.com/ElixirTeSS/TeSS_scrapers/blob/master/app/scrapers/enanomapper_scraper.rb) that can be applied to any of the repositories pages. 

There's 2 small tweaks we could do with:

1. Can you add a short description about training resources using the field-name 'about'? This would just ~ two sentences describing what the material is about.

2. Can you add some sort of map to where the resources will be? This is not critical as we can get write a solution to get around it; but it's good for Google visibility to. The simplest way is to create a file called [sitemap.xml that has a list of URLs ](http://www.advancedhtml.co.uk/robots-sitemaps.htm#sitemaps) 

**sitemap.xml**
```
Omics\ descriptors\ calculation/Omics\ descriptors\ calculation\ R\ package.md
BrowseOntology/Tutorial\ browsing\ eNM\ ontology.md
```

**Comment by egonw** [comment]
@njall, sorry that I did not have been able to pick this up in the past two weeks. But just a quick ping it's on my radar!

**Comment by egonw** [comment]
@njall, OK, I added the sitemap.xml now: https://github.com/enanomapper/tutorials/blob/master/sitemap.xml

I will now add `about` fields, but the Bioschemas.org specification says the object is of type `Thing` and not `Text`...

**Comment by egonw** [comment]
Added `about` fields for the three tutorials in the `sitemap.xml` now.

**Comment by njall** [comment]
Sitemap works perfectly, thanks! We've got a scraper ready now that pulls 3 materials in.
We've just got some issues with topics, audience, and the licence. The problem is on our end, I'll keep you posted when we solve it. The rest of the material metadata will appear on TeSS tomorrow morning!

**Comment by egonw** [comment]
Let me know if I can do something...

**Comment by njall** [comment]
Thanks, will do. 

Also, it might be a good idea to register eNanoMapper tools in bio.tools for more visibility. They have a manual registration form (you'll need to register for an account to add content)

**Comment by egonw** [comment]
yes, that's a key topic in the [OpenRiskNet](https://openrisknet.org/) project.

**Comment by egonw** [comment]
@njall, I think you said something about the URLs... but I cannot find the comment anymore... I should not use `@type: 'url'`, but what should it look like again?
