### ISSUE TITLE
Prepare 2018 ELIXIR All Hands meeting for new communities

### ISSUE THREAD

**Issue by egonw** [egonw/ELIXIR-Tox#8]

**Comment by egonw** [comment]
Slides being prepared: https://docs.google.com/presentation/d/12JS2vdjA9QNNrwyGznCfrpzXjlt9eXp7kLP732-1rzc/edit?usp=sharing

**Comment by egonw** [comment]
Good point... I will mention eTOX eTranSafe

On Jun 6, 2018 16:26, "Chris Evelo" <notifications@github.com> wrote:

What exactly went to the HoN for tomorrow’s decision? Was that this?

I thought we would involve more tox projects especially IMI projects. I
know that was done, but I do not see them on the slides. I see Ferran and
Alphonso mentioned though.

If you see this before your presentation I would still mention these
projects if you think that is correct

Also you might want to stress the data needs this community has (e.g. for
QSAR), the broad phenotype again (I just mentioned that from nutritional
perspective) and the extra societal challenge to (re)use data for read
across and such to reduce animal use.

Best Chris

**Comment by Chris-Evelo** [comment]
Nice. What you explained was better than the slides. Given that people (HoNs) might see the slides (not sure, are they online?) You might still want to update the slides
